# Generated by Django 5.1.2 on 2024-10-23 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoshUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultancyUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consultancy_name', models.CharField(max_length=150)),
                ('consultancy_dob', models.DateField()),
                ('consultancy_address', models.TextField()),
                ('consultancy_state', models.CharField(max_length=100)),
                ('consultancy_city', models.CharField(max_length=100)),
                ('consultancy_pincode', models.CharField(max_length=10)),
                ('consultancy_profile_pic', models.ImageField(blank=True, upload_to='users/')),
                ('consultancy_description', models.TextField(blank=True, max_length=500)),
                ('consultancy_current_member', models.CharField(blank=True, max_length=10)),
                ('consultancy_employee_count', models.CharField(blank=True, max_length=10)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consultancy User',
                'verbose_name_plural': 'Consultancy Users',
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='EstablishmentUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('setdate', models.DateField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('locationCount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='IndividualUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prefix', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=150)),
                ('mname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='users/')),
                ('aadhar', models.CharField(blank=True, max_length=20)),
                ('marital', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('current_member', models.CharField(blank=True, max_length=10)),
                ('association', models.CharField(blank=True, max_length=10)),
                ('firm_name', models.CharField(blank=True, max_length=150)),
                ('firm_uid', models.CharField(blank=True, max_length=15)),
                ('is_visible', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Individual User',
                'verbose_name_plural': 'Individual Users',
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='NGOUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ngo_name', models.CharField(max_length=150)),
                ('ngo_dob', models.DateField()),
                ('ngo_address', models.TextField()),
                ('ngo_state', models.CharField(max_length=100)),
                ('ngo_city', models.CharField(max_length=100)),
                ('ngo_pincode', models.CharField(max_length=10)),
                ('ngo_profile_pic', models.ImageField(blank=True, upload_to='users/')),
                ('ngo_description', models.TextField(blank=True, max_length=500)),
                ('ngo_current_member', models.CharField(blank=True, max_length=10)),
                ('ngo_employee_count', models.CharField(blank=True, max_length=10)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'NGO User',
                'verbose_name_plural': 'NGO Users',
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificationNameInput', models.CharField(max_length=100)),
                ('issuingOrganizationInput', models.CharField(max_length=100)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('credentialIdInput', models.CharField(blank=True, max_length=20, null=True)),
                ('credentialUrlInput', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComitteeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comittee_uid', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comitteecount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='ngo_documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_uid', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstate', models.CharField(blank=True, max_length=255, null=True)),
                ('loccity', models.CharField(blank=True, max_length=255, null=True)),
                ('locpincode', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInput', models.CharField(max_length=100)),
                ('companyNameInput', models.CharField(max_length=100)),
                ('currentlyWorkingInput', models.BooleanField(blank=True, default=False, null=True)),
                ('startDateexp', models.DateField(blank=True, null=True)),
                ('endDateexp', models.DateField(blank=True, null=True)),
                ('industryInput', models.CharField(blank=True, max_length=20, null=True)),
                ('locationInput', models.CharField(blank=True, max_length=20, null=True)),
                ('descriptionInputexp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PEDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_location', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_others', models.PositiveIntegerField(blank=True, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('vendorCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
                ('service_description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsInput', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHOEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('siteCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_base_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_others', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_id', to='posh.establishmentuser')),
            ],
        ),
    ]
