# Generated by Django 4.0.4 on 2024-06-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consultancy_name', models.CharField(max_length=150)),
                ('consultancy_dob', models.DateField()),
                ('consultancy_address', models.TextField()),
                ('consultancy_state', models.CharField(max_length=100)),
                ('consultancy_city', models.CharField(max_length=100)),
                ('consultancy_pincode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Consultancy User',
                'verbose_name_plural': 'Consultancy Users',
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='EstablishmentUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('setdate', models.DateField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('locationCount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('posh.poshuser',),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='association',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='current_member',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='firm_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='firm_uid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='ngo_current_member',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='ngo_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='ngo_employee_count',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='ngo_profile_pic',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_base_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_others', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHOEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('siteCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsInput', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
                ('service_description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('vendorCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PEDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_location', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_others', models.PositiveIntegerField(blank=True, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInput', models.CharField(max_length=100)),
                ('companyNameInput', models.CharField(max_length=100)),
                ('currentlyWorkingInput', models.BooleanField(blank=True, default=False, null=True)),
                ('startDateexp', models.DateField(blank=True, null=True)),
                ('endDateexp', models.DateField(blank=True, null=True)),
                ('industryInput', models.CharField(blank=True, max_length=20, null=True)),
                ('locationInput', models.CharField(blank=True, max_length=20, null=True)),
                ('descriptionInputexp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstate', models.CharField(blank=True, max_length=255, null=True)),
                ('loccity', models.CharField(blank=True, max_length=255, null=True)),
                ('locpincode', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_uid', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='ngo_documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComitteeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comittee_uid', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comitteecount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificationNameInput', models.CharField(max_length=100)),
                ('issuingOrganizationInput', models.CharField(max_length=100)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('credentialIdInput', models.CharField(blank=True, max_length=20, null=True)),
                ('credentialUrlInput', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
