# Generated by Django 4.2 on 2024-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='username',
            field=models.CharField(default='POS20240313161605', max_length=10, unique=True),
        ),
    ]
