# Generated by Django 4.0.4 on 2024-06-13 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consultancy_name', models.CharField(max_length=150)),
                ('consultancy_dob', models.DateField()),
                ('consultancy_address', models.TextField()),
                ('consultancy_state', models.CharField(max_length=100)),
                ('consultancy_city', models.CharField(max_length=100)),
                ('consultancy_pincode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Consultancy User',
                'verbose_name_plural': 'Consultancy Users',
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='EstablishmentUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('setdate', models.DateField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('locationCount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('posh.poshuser',),
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_base_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_others', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHOEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noHOEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('noDEPEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('siteCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('directEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpmale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('indirectEmpothers', models.PositiveIntegerField(blank=True, null=True)),
                ('vendorCount', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PEDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_location', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_male_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_female_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('deployed_others', models.PositiveIntegerField(blank=True, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstate', models.CharField(blank=True, max_length=255, null=True)),
                ('loccity', models.CharField(blank=True, max_length=255, null=True)),
                ('locpincode', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
