# Generated by Django 4.0.4 on 2024-06-11 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyUser',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consultancy_name', models.CharField(max_length=150)),
                ('consultancy_dob', models.DateField()),
                ('consultancy_address', models.TextField()),
                ('consultancy_state', models.CharField(max_length=100)),
                ('consultancy_city', models.CharField(max_length=100)),
                ('consultancy_pincode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Consultancy User',
                'verbose_name_plural': 'Consultancy Users',
            },
            bases=('posh.poshuser',),
        ),
    ]
