# Generated by Django 4.0.4 on 2024-05-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='username',
            field=models.CharField(default='POS20240530035231', max_length=10, unique=True),
        ),
    ]
