# Generated by Django 4.0.4 on 2024-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0002_individualuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='aadhar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='marital',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='username',
            field=models.CharField(default='POS20240324173304', max_length=10, unique=True),
        ),
    ]
