# Generated by Django 4.0.4 on 2024-06-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0002_consultancyuser_establishmentuser_vendordetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='association',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='current_member',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='firm_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='firm_uid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComitteeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comittee_uid', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comitteecount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
