# Generated by Django 4.0.4 on 2024-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0002_consultancyuser_establishmentuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyuser',
            name='consultancy_current_member',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='consultancyuser',
            name='consultancy_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='consultancyuser',
            name='consultancy_employee_count',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='consultancyuser',
            name='consultancy_profile_pic',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
