# Generated by Django 4.0.4 on 2024-03-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0003_individualuser_aadhar_individualuser_marital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='username',
            field=models.CharField(default='POS20240324185652', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='educations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_educations', to='posh.education'),
        ),
    ]
