# Generated by Django 4.0.4 on 2024-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0003_consultancyuser_consultancy_current_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyuser',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
