# Generated by Django 4.0.4 on 2024-06-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsInput', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInput', models.CharField(max_length=100)),
                ('companyNameInput', models.CharField(max_length=100)),
                ('currentlyWorkingInput', models.BooleanField(default=False)),
                ('startDateexp', models.DateField(blank=True, null=True)),
                ('endDateexp', models.DateField(blank=True, null=True)),
                ('industryInput', models.CharField(blank=True, max_length=20, null=True)),
                ('locationInput', models.CharField(blank=True, max_length=20, null=True)),
                ('descriptionInputexp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificationNameInput', models.CharField(max_length=100)),
                ('issuingOrganizationInput', models.CharField(max_length=100)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('credentialIdInput', models.CharField(blank=True, max_length=20, null=True)),
                ('credentialUrlInput', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
