# Generated by Django 4.0.4 on 2024-06-16 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0004_consultancyuser_is_visible_individualuser_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
