# Generated by Django 4.0.4 on 2024-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posh', '0005_skill_experience_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='currentlyWorkingInput',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
