# Generated by Django 5.0.6 on 2024-06-30 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posh', '0006_recruituser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('section', models.CharField(default='Third Year', max_length=100)),
                ('group_code', models.CharField(default='0000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posh.establishmentuser')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(default=datetime.time(10, 10))),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('instructions', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('submitted_time', models.TimeField(auto_now_add=True)),
                ('submitted_on_time', models.BooleanField(default=True)),
                ('submission_file', models.FileField(upload_to='documents/')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.employee')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.notice')),
            ],
        ),
    ]
